ifndef CRYPTECH_ROOT
  CRYPTECH_ROOT := $(abspath ../../../..)
endif

vpath %.c ${CRYPTECH_ROOT}/sw/thirdparty/libtfm/tomsfastmath
vpath %.h ${CRYPTECH_ROOT}/sw/thirdparty/libtfm/tomsfastmath

include ${CRYPTECH_ROOT}/sw/thirdparty/libtfm/tomsfastmath/makefile
