#!/usr/bin/env python
#
# Copyright (c) 2017, NORDUnet A/S All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# - Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# - Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
#
# - Neither the name of the NORDUnet nor the names of its contributors may
#   be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""
Console client shim to work with Cryptech Python multiplexer.
"""

import os
import sys
import socket
import atexit
import termios
import argparse

import tornado.iostream
import tornado.ioloop
import tornado.gen

class FemtoTerm(object):

    def __init__(self, s):
        self.termios_setup()
        self.stdin_stream  = tornado.iostream.PipeIOStream(sys.stdin.fileno())
        self.stdout_stream = tornado.iostream.PipeIOStream(sys.stdout.fileno())
        self.socket_stream = tornado.iostream.IOStream(s)
        self.closed = False

    def close(self):
        self.termios_teardown()
        self.stdin_stream.close()
        self.stdout_stream.close()
        self.socket_stream.close()
        self.closed = True

    @tornado.gen.coroutine
    def run(self):
        yield [self.stdout_loop(), self.stdin_loop()]

    def termios_setup(self):
        self.fd = sys.stdin.fileno()
        self.old_tcattr = termios.tcgetattr(self.fd)
        self.new_tcattr = termios.tcgetattr(self.fd)
        atexit.register(self.termios_teardown)
        self.new_tcattr[3] &= ~(termios.ICANON | termios.ECHO) #  | termios.ISIG
        self.new_tcattr[6][termios.VMIN] = 1
        self.new_tcattr[6][termios.VTIME] = 0
        termios.tcsetattr(self.fd, termios.TCSANOW, self.new_tcattr)

    def termios_teardown(self):
        if self.fd is not None:
            termios.tcsetattr(self.fd, termios.TCSAFLUSH, self.old_tcattr)
            self.fd = None

    @tornado.gen.coroutine
    def copy_loop(self, stream1, stream2, text1, text2, buffer_size = 1024):
        try:
            while not self.closed:
                buffer = yield stream1.read_bytes(buffer_size, partial = True)
                yield stream2.write(buffer.replace(text1, text2))
        except tornado.iostream.StreamClosedError:
            self.close()

    def stdin_loop(self):
        return self.copy_loop(self.stdin_stream, self.socket_stream, "\n", "\r")

    def stdout_loop(self):
        return self.copy_loop(self.socket_stream, self.stdout_stream, "\r\n", "\n")

def main():
    parser = argparse.ArgumentParser(formatter_class = argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("cty_socket",
                        nargs = "?",
                        help = "CTY PF_UNIX socket name",
                        default = os.getenv("CRYPTECH_CTY_CLIENT_SOCKET_NAME",
                                            "/tmp/.cryptech_muxd.cty"))
    args = parser.parse_args()

    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        s.connect(args.cty_socket)
    except socket.error:
        sys.exit("Couldn't connect to socket {}".format(args.cty_socket))
    tornado.ioloop.IOLoop.current().run_sync(FemtoTerm(s).run)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
