#!/bin/sh -
#
# Script to extract tables from the PKCS #11 specification and format
# them as YAML comment blocks.
#
# This isn't even half-assed, more like quarter-assed.  If I thought
# we'd be using it a lot I'd rewrite it in Python.
#
# Author: Rob Austein
# Copyright (c) 2015, NORDUnet A/S
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# - Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# - Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
#
# - Neither the name of the NORDUnet nor the names of its contributors may
#   be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

url=http://www.cryptsoft.com/pkcs11doc/download/pkcs11doc-v230.tgz

tar=${url##*/}

test -r $tar ||
wget $url ||
exit

tar -tf $tar |

awk '
  /group__SEC__(9|11)__.*\.html/ {

    n = split($0, a, "[/.]");
    title = a[n-1];

    n = split($0, a, /__/);
    s1 = a[3];
    s2 = (a[4] ~ /^[0-9]+$/) ? a[4] : 0;
    s3 = (a[5] ~ /^[0-9]+$/) ? a[5] : 0;
    idx = sprintf("%04d%04d%04d", s1, s2, s3);

    print idx, $0, title;
  }
' |

sort -n |

while read idx fn title
do

  tar -xOf $tar $fn |

  w3m -dump -O us-ascii -T text/html |

  awk -v title=$title '
    BEGIN {
      print "";
      print "###";
      print "#", title;
      print "###";
      print "";
    }
    /^[|+]/ {
      print "#", $0;
    }
  '

done
